### ISSUE TITLE
[Blocking] UnmodifiableUint8ListView Error as per latest flutter version (cannot update directly pineacl-0.5.1)

### ISSUE THREAD

**Issue by cs145442** [TerminalStudio/dartssh2#105]
As you can observe, with the latest flutter version, I'm unable to include dartSSH2 latest version due to internal changes. Could we take this up on priority as it's blocking my development. Thank you. 

Attached is the screenshot with the error. 
Also attached screenshot as I cannot update directly pineacl as its specific version is provided as dependency.

`
../../../../.pub-cache/hosted/pub.dev/pinenacl-0.5.1/lib/api/api.dart:90:12: Error: Method not found: 'UnmodifiableUint8ListView'.
    return UnmodifiableUint8ListView(Uint8List.fromList(data.toList()));
           ^^^^^^^^^^^^^^^^^^^^^^^^^
Target kernel_snapshot_program failed: Exception
`

`Resolving dependencies... (5.6s)
Because my_app depends on dartssh2 ^2.8.2 which depends on pinenacl ^0.5.0, pinenacl ^0.5.0 is required.
So, because my_app depends on pinenacl ^0.6.0, version solving failed.`

![image](https://github.com/user-attachments/assets/55f4826e-3e7f-4095-9d14-52a9f1b60469)

![image](https://github.com/user-attachments/assets/792b02e2-4eac-4e78-b717-47e23d1d6976)

**Comment by IoTServ** [comment]
Perhaps you can temporarily use [dartssh2_plus](https://pub.dev/packages/dartssh2_plus)

**Comment by maxhis** [comment]
A workaround is to override dependency:

```yaml
dependencies:
  dartssh2: ^2.8.2

dependency_overrides:
  pinenacl: ^0.6.0
```

**Comment by vicajilau** [comment]
This has been resolved on https://github.com/TerminalStudio/dartssh2/pull/106
