### ISSUE TITLE
Local port forwarding

### ISSUE THREAD

**Issue by FaFre** [TerminalStudio/dartssh2#11]
I tested the local port forwarding feature, but cannot get it running.

SSH Command I want to run: `ssh 172.17.0.2 -l root -L 1234:localhost:80`
With the dart client: `dart run dartssh.dart -l root 172.17.0.2 --debug --password test --tunnel localhost:80`

Is my command right at this point?

It says tunnel is up, but `curl 127.0.0.1:1234` responds connection refused.

**Comment by xtyxtyx** [comment]
Thanks for reporting the issue. Please try upgrading the version of the package to `2.1.0-pre` in pubspec.yaml or checkout the latest code from Github. Both local forwarding and remote forwarding are working now.
