### ISSUE TITLE
DiffieHellman is not show

### ISSUE THREAD

**Issue by dan12411** [TerminalStudio/dartssh2#12]
`SSHDiffieHellman` is comment out, could remove this comment, and show `EllipticCurveDiffieHellman`, `DiffieHellman` & `ScalarMult `? thanks :)
https://github.com/TerminalStudio/dartssh2/blob/3316b252ace4948f64812b7e5eca11f466d3f62d/lib/dartssh2.dart#L19

**Comment by xtyxtyx** [comment]
Since `2.0.0-pre` dartssh2 is completely rewritten and `SSHDiffieHellman` no longer exists.
