### ISSUE TITLE
Can I programmatically perform remote forwarding?

### ISSUE THREAD

**Issue by rohanpanuganti** [TerminalStudio/dartssh2#13]
Inside my main.dart I want to make a remote forwarding call like this:

`ssh -R 80:127.0.0.1:3000 user@<remote_server_ip>`

Is that currently possible and if so how would I go about doing it?

**Comment by xtyxtyx** [comment]
Since `2.0.0-pre` both local forwarding and remote forwarding have been implemented. For more details please refer to the [README](https://github.com/TerminalStudio/dartssh2#forward-connections-to-port-2222-on-the-server-to-local-port-22) and `example/` folder.
