### ISSUE TITLE
Copy file?

### ISSUE THREAD

**Issue by Migarl** [TerminalStudio/dartssh2#15]
Hi!

I want to copy a file (.tgz) from my host to the server (`scp` isn't available).

I tried
```
final session = await client.execute("tar -zxf -");
session.write(filebytes);
```
but without success. I think the problem is that `tar` don't know when he should stop listening on stdin.

I got the same result with `cat > file.tgz`.

Is there a way to copy a file from host to remote without `scp`?

Thanks for your help!

**Comment by xtyxtyx** [comment]
In 2.4.0 a new field [`stdin`](https://pub.dev/documentation/dartssh2/latest/dartssh2/SSHSession/stdin.html) is added to `SSHSession`, now it's possible to send data at full speed using streams:

```dart
final session = await client.execute('cat > file.txt');
await session.stdin.addStream(File('local_file.txt').openRead().cast());
```

and sending EOF to the remote process by closing the `stdin` sink:
```dart
await session.stdin.close(); // Closing the sink sends EOF to the remote process.
await session.done;
```
