### ISSUE TITLE
Create and Write to file

### ISSUE THREAD

**Issue by yinhang1107** [TerminalStudio/dartssh2#16]
Hi, I was trying to create a text file and write to it. However, every time I run the test, I was able to create the file or write to the file but got an error when I wanted to create and write to it. Below is my example.

void main() {
  test('', () async {
    final socket = await SSHSocket.connect('localhost', 22);

    final client = SSHClient(
      socket,
      username: 'yh',
      onPasswordRequest: () => 'secret',
    );

    final sftp = await client.sftp();
    await sftp.open(
      'asdf.txt',
      mode: SftpFileOpenMode.create,
    );

    final file1 = await sftp.open('asdf.txt', mode: SftpFileOpenMode.write);
    final lists = 'asdfasdf'.codeUnits;
    await file1.writeBytes(Uint8List.fromList(lists));

    client.close();
    await client.done;
  });
}

**Comment by xtyxtyx** [comment]
Hello,
could you provide the error message you got along with the backtrack
? So I can make further investigations.

**Comment by yinhang1107** [comment]
![image](https://user-images.githubusercontent.com/75302725/149447099-dbf91814-bb5f-4c94-b5e4-fab229ccedcc.png)

**Comment by xtyxtyx** [comment]
On my machines the example you provided works without throwing any exception so I'm not able to reproduce the problem you encountered.

It's my guess that the sftp server you use may not support opening a file twice.

You can try combining `SftpFileOpenMode.create` and `SftpFileOpenMode.write` to one flag when opening the file:
```dart
final file1 = await sftp.open('asdf.txt', mode: SftpFileOpenMode.create | SftpFileOpenMode.write);
```

or close the file you opened first before opening the second:
```dart
final file = await sftp.open('asdf.txt', mode: SftpFileOpenMode.create);
await file.close();

final file1 = await sftp.open('asdf1.txt', mode: SftpFileOpenMode.write);
...
```

If that doesn't work please tell me the sftp server and os you use and I'll have a look.

**Comment by yinhang1107** [comment]
Both of the solutions you provided works. Thanks a lot!
