### ISSUE TITLE
Question: Server auth requires keyboard interaction.

### ISSUE THREAD

**Issue by ShadowOfThePenguin** [TerminalStudio/dartssh2#25]
I know this is kind of an edge case, however I am trying to log into the sftp server of a piece of equipment I work with, and it requires some sort of keyboard interaction with the cl as part of the password. I have been poking around several different packages, and have not been able to figure out how this works. I was able to sign in using the node library 'ssh2-sftp-client' with the parameter of 'tryKeyboard' set to true. I would really prefer to build this as a flutter app, instead of js. Is there a way in the 'onPasswordRequest' function that I can add this keyboard interaction?

**Comment by xtyxtyx** [comment]
> Is there a way in the 'onPasswordRequest' function that I can add this keyboard interaction?

Yes. Keyboard interactive authentication is enabled when the [`onUserInfoRequest`](https://pub.dev/documentation/dartssh2/latest/dartssh2/SSHClient/onUserInfoRequest.html) field is set.

**Comment by xtyxtyx** [comment]
Usage of `onUserInfoRequest` can be find here: https://github.com/TerminalStudio/dartssh2/blob/master/bin/src/ssh_shared.dart#L21

**Comment by ShadowOfThePenguin** [comment]
It was in the API in multiple locations, and I somehow still managed to miss it. Thanks so much for the quick response and the excellent resources.
