### ISSUE TITLE
lib/src/ssh_key_pair.dart(405,50): error GD65BB2B6: The getter 'buffer' isn't defined for the class 'SignedMessage'. 

### ISSUE THREAD

**Issue by jonahzheng** [TerminalStudio/dartssh2#35]
![W1FXLFU_ I_CYK~NFBC7O%1](https://user-images.githubusercontent.com/5125282/177533189-e1d94a5d-e3fb-4cf5-bbeb-4bfbeae2775f.png)

pinenacl v0.3.5

**Comment by felix-barz-brickmakers** [comment]
Temporarily force-downgrading pinenacl to 0.3.4 will help. However, This package should be updated to work with the latest version of pinenacl!

```yaml
dependency_overrides:
  pinenacl: 0.3.4 # Until https://github.com/TerminalStudio/dartssh2/issues/35 was fixed
```

**Comment by jonahzheng** [comment]
@felix-barz-brickmakers yes,I know it, pinenacl v0.3.4 is ok.

**Comment by jonahzheng** [comment]
@xtyxtyx thank you for you job
