### ISSUE TITLE
can this lib update win32 lib version to 3.0?

### ISSUE THREAD

**Issue by TEENSTITANS** [TerminalStudio/dartssh2#43]
can this lib update win32 to version 3.0?

**Comment by xtyxtyx** [comment]
Fixed in `2.7.3`. `win32` was previously used to implement the `dartssh` and `dartsftp` command-line tools. Since `2.7.3` those command-line tools are moved to separate packages so `win32` is no longer required.

**Comment by TEENSTITANS** [comment]
Great job👍, thanks a lot for the reply🙂, I saw the latest version 2.7.3 on pub.

so i close this issue.
