### ISSUE TITLE
Halting when uploading 0 bytes files.

### ISSUE THREAD

**Issue by gaddlord** [TerminalStudio/dartssh2#50]
When attempting to SFTP upload an empty file (with 0 bytes in size) the upload halts (neither raises an error, no exits the program).

The client machine where the program is executes is Windows the remote one is Amazon Linux 2.

One might wonder what is the use case for such files. Sometime programs create programx.lock files which are used as a persisted on file system boolean switch.

**Comment by obemu** [comment]
Most likely same issue as [#100](https://github.com/TerminalStudio/dartssh2/issues/100), see [my fix](https://github.com/TerminalStudio/dartssh2/issues/100#issuecomment-2258373338)

**Comment by vicajilau** [comment]
Many thanks!! This has been resolved in the next release
