### ISSUE TITLE
How to listen on session disconnect

### ISSUE THREAD

**Issue by gaiththewolf** [TerminalStudio/dartssh2#61]
When typing exit command on ssh active session,I recove logout and I need to close the ssh screen.

This is my session code :

      session = await client?.shell( 
         pty: SSHPtyConfig( 
           width: terminal.viewWidth, 
           height: terminal.viewHeight, 
         ), 
       );

I tried using session.exitCode but this not firing event it's just a check if session still alive or not.

**Comment by xtyxtyx** [comment]
Thanks for your interest in this package. [SSHSession.done](https://pub.dev/documentation/dartssh2/latest/dartssh2/SSHSession/done.html) can be used to wait for the session to close.

**Comment by gaiththewolf** [comment]
perfect, thanks a lot 👍🏼
