### ISSUE TITLE
Question: Is there any way to track SFTP file upload progress?

### ISSUE THREAD

**Issue by prinzpiuz** [TerminalStudio/dartssh2#67]

**Comment by prinzpiuz** [comment]
sorry, my mistake didn't find `onProgress` callback

**Comment by ganeshchenniah** [comment]
Did u find solution ? i m looking to show progress bar for sftp transfer .

**Comment by prinzpiuz** [comment]
> Did u find solution ? i m looking to show progress bar for sftp transfer .

you can use `onProgress`

**Comment by ganeshchenniah** [comment]
HI,
Thanks for you reply.

I m using below code to upload data .  May i know where to add onProgress call . BTW i m using linux platform. 

 client = SSHClient(
        await SSHSocket.connect('$ip', 22),
        username: 'root',
        onPasswordRequest: () => 'passwd',
        // printTrace:print,
        // printDebug: print,
      );
 final sftp = await client.sftp();
      await client.authenticated;

final file = await sftp.open('file.tgz, mode: SftpFileOpenMode.create | SftpFileOpenMode.write );
      await file.write(File('${appDocPath}/file.tgz').openRead().cast());

**Comment by prinzpiuz** [comment]
`await file.write(File('${appDocPath}/file.tgz').openRead().cast(), onProgress: (total) => print(total));`

**Comment by ganeshchenniah** [comment]
Appreciate your valuable time

i have another requirement to copy from IP to IP
example :
In linux we do : scp source and destination . Is there a way we can implement the scp/sftp with progress  ?
