### ISSUE TITLE
sftp stuck right after transfer completion

### ISSUE THREAD

**Issue by ganeshchenniah** [TerminalStudio/dartssh2#71]
I m using below code to upload data . May i know where to add onProgress call . BTW i m using linux platform.

client = SSHClient(
await SSHSocket.connect('$ip', 22),
username: 'root',
onPasswordRequest: () => 'passwd',
// printTrace:print,
// printDebug: print,
);
final sftp = await client.sftp();

The below code gets stuck right after transfer completion sometimes . Do you know how to over come ?
sftp
await file.write(File('${appDocPath}/file.tgz').openRead().cast(), onProgress: (total) => print(total));

**Comment by ganeshchenniah** [comment]
Any Update on this issue ? It still gets stuck after 100% transfer completion. Should we do any sync or something .

**Comment by brahimmasmudi** [comment]
i have the same problem , i tried deleting the files from my local storage after the upload is completed but it didn't work , also , this doesn't happen every time , sometimes the transfer doesn't get stuck after completion

**Comment by obemu** [comment]
Same problem as [#100](https://github.com/TerminalStudio/dartssh2/issues/100), see [my fix](https://github.com/TerminalStudio/dartssh2/issues/100#issuecomment-2258373338)

**Comment by vicajilau** [comment]
Duplicated and fixed. Many thanks for opening this
