### ISSUE TITLE
how to catch failed authentication?

### ISSUE THREAD

**Issue by tiwwwi** [TerminalStudio/dartssh2#76]
for example with something like this: 
'''
sshConnect() async {
  final client = SSHClient(
    await SSHSocket.connect(allConfigs.host, int.parse(allConfigs.port)),
    username: allConfigs.user,
    onPasswordRequest: () => allConfigs.pass,
  );
  return client;
} 
 try {
    client = await sshConnect();
  } catch (e) {
    return 'Error connect: $e';
  }
'''
if I try to connect with an invalid host or invalid port  then  the error is catched  and I can warn the user in my interface. But if the user or pass is invalid   It never returns..  I'm guessing its waiting for the user to try with another password but since I'm not in interactive mode their is no way to catch that?

**Comment by xtyxtyx** [comment]
Hi, 

Thank you for your interest in this package. You can use the [`client.authenticated`](https://pub.dev/documentation/dartssh2/latest/dartssh2/SSHClient/authenticated.html) Future to wait for the authentication to complete or catch any errors. For example:

```dart
final client = SSHClient(
  await SSHSocket.connect('...', 22),
  username: '...',
);

try {
  await client.authenticated;
} on SSHAuthAbortError catch (e) {
  print("authentication aborted: ${e.message}");
} on SSHAuthError catch (e) {
  print("failed to authenticate: ${e.message}");
}

print(client.remoteVersion);
```

**Comment by tiwwwi** [comment]
Works perfectly! Thanks ;)

**Comment by harmptor** [comment]
I was going crazy until I found this. Works like a charm. I think you should put this in the README with the other examples! :) @xtyxtyx
