### ISSUE TITLE
SSHAuthFailError(All authentication methods failed)

### ISSUE THREAD

**Issue by nevishs** [TerminalStudio/dartssh2#94]
problem solved

**Comment by XavierChanth** [comment]
@nevishs Instead of replacing the details of your issue with "problem solved", next time document the solution in case someone else has the same issue in the future.

**Comment by nevishs** [comment]
@XavierChanth, actually it was not an issue (just a problem in my end). I guess there is no option to remove this issue, right?

**Comment by psvm** [comment]
@nevishs I have a same problem. Can you explain how did you solve it?
